"""Generate a standalone converter and a Colab notebook from the reviewed source.

Uses only stdlib; does not install conversion dependencies or execute conversion.
"""
import ast
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEST = ROOT / "scripts/alphabet/colab"
DEST.mkdir(exist_ok=True)

def read(name):
    return (ROOT / name).read_text(encoding="utf-8")

sources = {
    name: read(name) for name in (
        "VOYA-Collector/processed/train_utils/models/base.py",
        "VOYA-Collector/processed/train_utils/models/bigru_attention.py",
        "VOYA-Collector/processed/shared/normalization.py",
    )
}
code = read("scripts/alphabet/deploy.py")
code = code.replace("from __future__ import annotations\n", "")
code = code.replace('ROOT = Path(__file__).resolve().parents[2]', 'ROOT = Path(__file__).resolve().parent')
code = code.replace('sys.path.insert(0, str(ROOT / "VOYA-Collector"))\n', '')
code = code.replace('from processed.train_utils.models.bigru_attention import BiGRUAttentionModel\n', '')
code = code.replace('from processed.shared.normalization import normalize_hands_vector_126\n', '')
code = code.replace('p.add_argument("--contract", default="scripts/alphabet/deployment_contract.json")',
                    'p.add_argument("--contract", help="Optional override of the embedded, hash-pinned contract")')
code = code.replace('contract = json.loads(local(args.contract).read_text(encoding="utf-8"))',
                    'contract = json.loads(local(args.contract).read_text(encoding="utf-8")) if args.contract else json.loads(EMBEDDED_CONTRACT_JSON)')
code = code.replace('"resolvedModelConfig": model.get_config(),', '"modelSourceSha256": MODEL_SOURCE_SHA256, "resolvedModelConfig": model.get_config(),')

parts = [
    '# Generated by scripts/alphabet/build_colab.py. Standalone, original BiGRU architecture.\n',
    '# Run on Colab/Linux: python convert_alphabet_colab.py convert --output-dir output_run_1\n',
    'from __future__ import annotations\n',
]
for name, source in sources.items():
    source = source.replace('from .base import SignLanguageModel, initialize_kaiming\n', '')
    parts += [f'\n# Original source: {name}\n', source, '\n']
parts += [
    '\nEMBEDDED_CONTRACT_JSON = ' + repr(read("scripts/alphabet/deployment_contract.json")) + '\n',
    'MODEL_SOURCE_SHA256 = ' + repr({name: hashlib.sha256(source.encode()).hexdigest() for name, source in sources.items()}) + '\n',
    code,
]
standalone = ''.join(parts)
ast.parse(standalone)
script_path = DEST / "convert_alphabet_colab.py"
script_path.write_text(standalone, encoding="utf-8")

def markdown(text):
    return {"cell_type": "markdown", "metadata": {}, "source": text.splitlines(keepends=True)}

def cell(text):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": text.splitlines(keepends=True)}

install = '''# Chỉ cài trong máy Linux của Colab. CPU đủ dùng; không cần GPU.
# Dùng virtualenv riêng để tránh xung đột torch/numpy có sẵn của Colab.
import os, sys, subprocess
from pathlib import Path
assert sys.platform == "linux", "Cell này dành cho Google Colab/Linux."
assert (3, 10) <= sys.version_info[:2] <= (3, 13), "Chọn runtime Python 3.10–3.13."
os.chdir("/content")
VENV = Path("/content/alphabet_converter_env")
if not (VENV / "bin/python").exists():
    subprocess.run([sys.executable, "-m", "venv", str(VENV)], check=False)
PYTHON = str(VENV / "bin/python")
pip_ready = (VENV / "bin/python").exists() and subprocess.run(
    [PYTHON, "-m", "pip", "--version"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
).returncode == 0
if not pip_ready:
    # Một số image Colab thiếu ensurepip/python-venv; không cần apt hoặc restart.
    subprocess.run([sys.executable, "-m", "pip", "install", "virtualenv==20.35.3"], check=True)
    subprocess.run([sys.executable, "-m", "virtualenv", str(VENV)], check=True)
subprocess.run([PYTHON, "-m", "pip", "install", "--upgrade", "pip"], check=True)
subprocess.run([PYTHON, "-m", "pip", "install", "torch==2.11.0", "torchao==0.17.0",
                "--index-url", "https://download.pytorch.org/whl/cpu"], check=True)
subprocess.run([PYTHON, "-m", "pip", "install", "litert-torch==0.9.4", "litert-converter==0.4.0",
                "ai-edge-litert==2.2.0", "numpy==2.1.3", "torch==2.11.0", "torchao==0.17.0"], check=True)
subprocess.run([PYTHON, "-c", "import torch, litert_torch; print('torch:', torch.__version__); print('litert_torch:', litert_torch.__version__)"], check=True)
print("Đã chuẩn bị xong môi trường conversion.")
'''
upload = '''from google.colab import files
from pathlib import Path
import hashlib
os.chdir("/content")
CHECKPOINT = Path("bigru_attention_alphabet_20260818_114440.pt")
if not CHECKPOINT.exists():
    print("Chọn file bigru_attention_alphabet_20260818_114440.pt từ máy của bạn.")
    files.upload()
assert CHECKPOINT.exists(), f"Thiếu {CHECKPOINT.name}"
assert hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest() == "0f6626b2857827645c7139e4870d02cfd905e5fcf9c3b4d879d266415f0237eb", "Checkpoint không phải file đã kiểm tra trong dự án."
print("Checkpoint đúng SHA-256.")
# Không bắt buộc: nếu có bộ test thực, upload test_data.npz bằng panel Files.
# Định dạng: x float32 [N,60,126] đã normalize đúng lúc train;
# y int [N] là class index từ checkpoint (0..29), optional sample_ids [N].
TEST_DATA = Path("/content/test_data.npz")
'''
run = '''import datetime, json, subprocess, shutil
from pathlib import Path
from google.colab import files
RUN = Path("/content") / ("alphabet_export_" + datetime.datetime.now().strftime("%Y%m%d_%H%M%S_%f"))
LOG = Path(str(RUN) + ".log")
cmd = [PYTHON, "/content/convert_alphabet_colab.py", "convert", "--checkpoint", str(CHECKPOINT.resolve()), "--output-dir", str(RUN)]
if TEST_DATA.exists():
    cmd += ["--test-data", str(TEST_DATA)]
print("Đang convert FP32 và kiểm tra 64 golden sequences. Có thể mất vài phút.")
# Lưu toàn bộ log, kể cả lỗi import/export/conversion/parity.
with LOG.open("w", encoding="utf-8") as log:
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                               text=True, encoding="utf-8", errors="replace", bufsize=1)
    for line in process.stdout:
        print(line, end="")
        log.write(line)
    exit_code = process.wait()
RUN.mkdir(exist_ok=True)
shutil.copyfile(LOG, RUN / "conversion.log")
with (RUN / "requirements-frozen.txt").open("w") as f:
    subprocess.run([PYTHON, "-m", "pip", "freeze"], stdout=f, check=True)
report_path = RUN / "report.json"
report = json.loads(report_path.read_text()) if report_path.exists() else {}
passed = exit_code == 0 and report.get("pythonParityPassed") is True and report.get("newConversionExecuted") is True
status = "PASS" if passed else "FAILED"
if passed:
    for stage in ["afterConvertParity", "serializedTfliteParity", "convertVsReloadParity"]:
        print(stage, json.dumps(report[stage], indent=2))
    print("PASS: TFLite FP32 đã vượt qua kiểm tra PyTorch → convert → serialize/load lại.")
else:
    print("FAILED: chưa sử dụng model này trong app. Gửi ZIP chứa log lại để kiểm tra.")
archive = shutil.make_archive(str(RUN) + "_" + status, "zip", root_dir=RUN)
print("Tải ZIP này về và gửi lại trong cuộc trò chuyện:", Path(archive).name)
files.download(archive)
'''
notebook = {
    "nbformat": 4, "nbformat_minor": 5,
    "metadata": {"colab": {"name": "Convert_Alphabet_FP32.ipynb"}, "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}},
    "cells": [
        markdown("# Chuyển BiGRU Alphabet sang TFLite FP32\n\nMở notebook trong Google Colab, chọn **Runtime → Run all**, upload checkpoint khi được hỏi, rồi gửi lại file ZIP kết quả.\n\nKiến trúc lấy nguyên từ VOYA-Collector; model hidden=64, 2 GRU layers, dropout=0.3 được kiểm chứng bằng weights. Nhãn lấy từ checkpoint. Không quantize/retrain. Chuỗi test có cấu trúc landmark kiểm tra độ khớp số học; accuracy thực cần thêm `test_data.npz`.\n\nDependencies chỉ cài trong Colab. Không cần bật GPU. [LiteRT Torch](https://github.com/google-ai-edge/litert-torch), [torch/torchao compatibility](https://github.com/pytorch/ao/issues/2919)."),
        cell(install),
        cell(upload),
        markdown("## Python converter độc lập\nCell dưới ghi file Python; có thể thu gọn cell sau khi chạy."),
        cell("%%writefile /content/convert_alphabet_colab.py\n" + standalone),
        cell(run),
    ],
}
path = DEST / "Convert_Alphabet_FP32.ipynb"
for index, c in enumerate(notebook["cells"]):
    c["id"] = f"alphabet-{index:02d}"
path.write_text(json.dumps(notebook, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
for c in notebook["cells"]:
    if c["cell_type"] == "code":
        source = ''.join(c["source"])
        if source.startswith("%%writefile"):
            source = source.split('\n', 1)[1]
        ast.parse(source)
print(f"Created {script_path.relative_to(ROOT)} ({script_path.stat().st_size} bytes)")
print(f"Created {path.relative_to(ROOT)} ({path.stat().st_size} bytes); Python cells parse successfully")
